name: 'Apply D1 Updates'
description: 'Apply incremental updates (upserts + deletes) to a Cloudflare D1 database'

inputs:
  database-name:
    description: 'D1 database name (e.g., geocoder-divisions-global)'
    required: true
  diff-path:
    description: 'Path to the diff SQL files (e.g., exports/diff)'
    required: true
  has-changes:
    description: 'Whether there are changes to apply'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Show diff stats
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Diff stats for ${{ inputs.database-name }}:"
        cat ${{ inputs.diff-path }}/stats.json

    - name: Apply upserts
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Applying upserts to ${{ inputs.database-name }}..."
        npx wrangler d1 execute ${{ inputs.database-name }} \
          --remote \
          --file=${{ inputs.diff-path }}/upserts.sql

    - name: Apply deletes
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Applying deletes to ${{ inputs.database-name }}..."
        npx wrangler d1 execute ${{ inputs.database-name }} \
          --remote \
          --file=${{ inputs.diff-path }}/deletes.sql

    - name: Update metadata
      if: inputs.has-changes == 'true'
      shell: bash
      run: |
        echo "Updating metadata for ${{ inputs.database-name }}..."
        npx wrangler d1 execute ${{ inputs.database-name }} \
          --remote \
          --file=${{ inputs.diff-path }}/metadata.sql
